#### Selecionar qual base de dados carregar

In [7]:
# Imports

import pandas as pd
import sklearn as skl
import matplotlib as plt
import scipy.io as sci
import numpy as np

### Single

In [54]:
# Pré-carregamento

avi_data = list()

for i in range(1,5):
    avi_data.append(sci.loadmat(f"../datasets/avi/single/Sub{i}_singletarget.mat"))

In [55]:
# Extração direta dos dados

X = [d['Data'][0][0][0] for d in avi_data]
y = [d['Data'][0][0][1] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(15360, 27)
(15360, 26)
(15360, 21)
(15360, 21)

Divisão dos rótulos (sequências):
[[10.  10.  10.  12.  12.  12.   6.5  6.5  6.5  6.   6.   6.   6.   6.
   6.   7.5  7.5  7.5  7.   7.   7.   8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.
   7.   7.   7.   7.   7.   8.2  8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.   7.
   7.   8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.   7.
   7.   8.2  8.2  8.2  9.3  9.3  9.3]]


In [64]:
# Padronizando os participantes 

full_data_X = list()
full_data_y = list()

full_data_X.append((X[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))]).T)
full_data_y.append((y[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))]).T)

full_data_X.append((X[1][:, list(set(range(26)) - set([6, 16, 17, 18, 22]))]).T)
full_data_y.append((y[1][:, list(set(range(26)) - set([6, 16, 17, 18, 22]))]).T)

full_data_X.append((X[2][:, :]).T)
full_data_y.append((y[2][:, :]).T)

full_data_X.append((X[3][:, :]).T)
full_data_y.append((y[3][:, :]).T)

full_data_X = np.array(full_data_X)
full_data_y = np.array(full_data_y)
full_data_X.shape, full_data_y.shape

# Salvar os dados numpy

# np.save("../datasets/avi/single/data_sub1.npy", full_data_X)
# np.save("../datasets/avi/single/labels_sub1.npy", full_data_y)

((4, 21, 15360), (4, 21, 1))

In [11]:
full_data_X.shape, full_data_y.shape

((4, 15360, 21), (4, 1, 21))

In [59]:
a = full_data_X.shape
full_data_X = full_data_X.reshape([a[0], a[2], a[1]])
full_data_X.shape

(4, 21, 15360)

### Multi

In [44]:
# Pré-carregamento

avi_data_multi = list()

for i in range(1,6):
    for j in range(1,3):
        avi_data_multi.append(sci.loadmat(f"../datasets/avi/multi/Sub{i}_{j}_multitarget"))

In [49]:
# Extração direta dos dados

X = [d['Data'][0][0][7] for d in avi_data_multi]
y = [d['Data'][0][0][8][0] for d in avi_data_multi]

print("Divisão dos dados:")
for data in X:
    # data = data.swapaxes()
    print(data.T.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)
(10, 8192)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
